//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_Auditoria_TB
    {
        public int IdAuditoria { get; set; }
        public string TablaAfectada { get; set; }
        public string Modulo { get; set; }
        public string Accion { get; set; }
        public string Campo { get; set; }
        public string IdRegistro { get; set; }
        public string ValorAnterior { get; set; }
        public string ValorNuevo { get; set; }
        public string UsuarioSistema { get; set; }
        public System.DateTime FechaAuditoria { get; set; }
        public string Observacion { get; set; }
    }
}
