//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_Auditoria_TB
    {
        public int IdAuditoria { get; set; }
        public string TablaAfectada { get; set; }
        public string Modulo { get; set; }
        public string Accion { get; set; }
        public string Campo { get; set; }
        public string IdRegistro { get; set; }
        public string ValorAnterior { get; set; }
        public string ValorNuevo { get; set; }
        public string UsuarioSistema { get; set; }
        public System.DateTime FechaAuditoria { get; set; }
        public string Observacion { get; set; }
    }
}
