//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_Auditoria_TB
    {
        public int IdAuditoria { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> IdAdmin { get; set; }
        public Nullable<int> IdUsuarioAfectado { get; set; }
        public string Modulo { get; set; }
        public string Accion { get; set; }
        public string Campo { get; set; }
        public string ValorAnterior { get; set; }
        public string ValorNuevo { get; set; }
        public string Observacion { get; set; }
    
        public virtual MH_Usuario_TB MH_Usuario_TB { get; set; }
        public virtual MH_Usuario_TB MH_Usuario_TB1 { get; set; }
    }
}
