//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_Cita_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MH_Cita_TB()
        {
            this.MH_Servicios_Cita_TB = new HashSet<MH_Servicios_Cita_TB>();
        }
    
        public int IdCita { get; set; }
        public int IdUsuario { get; set; }
        public int IdMascota { get; set; }
        public int IdEstado { get; set; }
        public System.DateTime FechaHoraCita { get; set; }
        public string NotasCliente { get; set; }
        public string NotasInternas { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualiza { get; set; }
    
        public virtual MH_Estado_TB MH_Estado_TB { get; set; }
        public virtual MH_Mascotas_TB MH_Mascotas_TB { get; set; }
        public virtual MH_Usuario_TB MH_Usuario_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_Servicios_Cita_TB> MH_Servicios_Cita_TB { get; set; }
    }
}
