//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_Comision_TB
    {
        public int IdComision { get; set; }
        public int IdUsuario { get; set; }
        public string TipoComision { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
        public Nullable<decimal> MontoFijo { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual MH_Usuario_TB MH_Usuario_TB { get; set; }
    }
}
