//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_Canton_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MH_Canton_TB()
        {
            this.MH_Distrito_TB = new HashSet<MH_Distrito_TB>();
        }
    
        public int IdCanton { get; set; }
        public int IdProvincia { get; set; }
        public string NombreCanton { get; set; }
    
        public virtual MH_Provincia_TB MH_Provincia_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_Distrito_TB> MH_Distrito_TB { get; set; }
    }
}
