//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_Direccion_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MH_Direccion_TB()
        {
            this.MH_Usuario_TB = new HashSet<MH_Usuario_TB>();
        }
    
        public int IdDireccion { get; set; }
        public int IdDistrito { get; set; }
        public string Detalle { get; set; }
        public string CodigoPostal { get; set; }
    
        public virtual MH_Distrito_TB MH_Distrito_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_Usuario_TB> MH_Usuario_TB { get; set; }
    }
}
