//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_Distrito_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MH_Distrito_TB()
        {
            this.MH_Direccion_TB = new HashSet<MH_Direccion_TB>();
        }
    
        public int IdDistrito { get; set; }
        public int IdCanton { get; set; }
        public string NombreDistrito { get; set; }
    
        public virtual MH_Canton_TB MH_Canton_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_Direccion_TB> MH_Direccion_TB { get; set; }
    }
}
