//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_DetalleFactura_TB
    {
        public int IdDetalleFactura { get; set; }
        public int IdFactura { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> IdServicio { get; set; }
        public string Descripcion { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }
        public decimal Subtotal { get; set; }
    
        public virtual MH_Factura_TB MH_Factura_TB { get; set; }
        public virtual MH_Productos_TB MH_Productos_TB { get; set; }
        public virtual MH_Servicios_TB MH_Servicios_TB { get; set; }
    }
}
