//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_EmpleadoJornada_TB
    {
        public int IdEmpleadoJornada { get; set; }
        public int IdUsuario { get; set; }
        public int IdJornada { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public bool Activa { get; set; }
    
        public virtual MH_Jornada_TB MH_Jornada_TB { get; set; }
        public virtual MH_Usuario_TB MH_Usuario_TB { get; set; }
    }
}
