//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_EmpleadoLaboral_TB
    {
        public int IdEmpleadoLaboral { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaInicioContrato { get; set; }
        public Nullable<System.DateTime> FechaFinContrato { get; set; }
        public decimal SalarioHora { get; set; }
        public Nullable<decimal> SalarioMensual { get; set; }
        public bool EsMensual { get; set; }
        public bool Activo { get; set; }
    
        public virtual MH_Usuario_TB MH_Usuario_TB { get; set; }
    }
}
