//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_Factura_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MH_Factura_TB()
        {
            this.MH_DetalleFactura_TB = new HashSet<MH_DetalleFactura_TB>();
        }
    
        public int IdFactura { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public int IdEstado { get; set; }
        public string MetodoPago { get; set; }
        public string NumeroReferencia { get; set; }
        public decimal MontoTotal { get; set; }
        public string Observaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_DetalleFactura_TB> MH_DetalleFactura_TB { get; set; }
        public virtual MH_Estado_TB MH_Estado_TB { get; set; }
        public virtual MH_Usuario_TB MH_Usuario_TB { get; set; }
    }
}
