//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_Jornada_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MH_Jornada_TB()
        {
            this.MH_EmpleadoJornada_TB = new HashSet<MH_EmpleadoJornada_TB>();
        }
    
        public int IdJornada { get; set; }
        public string Nombre { get; set; }
        public System.TimeSpan HoraEntradaBase { get; set; }
        public System.TimeSpan HoraSalidaBase { get; set; }
        public int MinAlmuerzo { get; set; }
        public int ToleranciaMin { get; set; }
        public Nullable<decimal> HorasPorDia { get; set; }
        public bool Activa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_EmpleadoJornada_TB> MH_EmpleadoJornada_TB { get; set; }
    }
}
