//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_Jornada_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MH_Jornada_TB()
        {
            this.MH_EmpleadoJornada_TB = new HashSet<MH_EmpleadoJornada_TB>();
        }
    
        public int IdJornada { get; set; }
        public string Nombre { get; set; }
        public System.TimeSpan HoraEntradaBase { get; set; }
        public System.TimeSpan HoraSalidaBase { get; set; }
        public int MinAlmuerzo { get; set; }
        public int ToleranciaMin { get; set; }
        public Nullable<decimal> HorasPorDia { get; set; }
        public bool Activa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_EmpleadoJornada_TB> MH_EmpleadoJornada_TB { get; set; }
    }
}
