//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_Marcacion_TB
    {
        public long IdMarcacion { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime HoraEntrada { get; set; }
        public Nullable<System.DateTime> HoraSalida { get; set; }
        public string Observacion { get; set; }
        public bool Aprobada { get; set; }
    
        public virtual MH_Usuario_TB MH_Usuario_TB { get; set; }
    }
}
