//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_Mascotas_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MH_Mascotas_TB()
        {
            this.MH_Cita_TB = new HashSet<MH_Cita_TB>();
        }
    
        public int IdMascota { get; set; }
        public int IdUsuario { get; set; }
        public int IdEspecie { get; set; }
        public Nullable<int> IdRaza { get; set; }
        public string NombreMascota { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Observaciones { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_Cita_TB> MH_Cita_TB { get; set; }
        public virtual MH_Especie_TB MH_Especie_TB { get; set; }
        public virtual MH_Raza_TB MH_Raza_TB { get; set; }
        public virtual MH_Usuario_TB MH_Usuario_TB { get; set; }
    }
}
