//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_Marcacion_TB
    {
        public int IdMarcacion { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> HoraEntrada { get; set; }
        public Nullable<System.DateTime> HoraSalida { get; set; }
        public string Observacion { get; set; }
    
        public virtual MH_Usuario_TB MH_Usuario_TB { get; set; }
    }
}
