//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_Mascotas_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MH_Mascotas_TB()
        {
            this.MH_Cita_TB = new HashSet<MH_Cita_TB>();
            this.MH_Recomendaciones_TB = new HashSet<MH_Recomendaciones_TB>();
        }
    
        public int IdMascota { get; set; }
        public int IdUsuario { get; set; }
        public int IdEspecie { get; set; }
        public Nullable<int> IdRaza { get; set; }
        public string NombreMascota { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Observaciones { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_Cita_TB> MH_Cita_TB { get; set; }
        public virtual MH_Especie_TB MH_Especie_TB { get; set; }
        public virtual MH_Raza_TB MH_Raza_TB { get; set; }
        public virtual MH_Usuario_TB MH_Usuario_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_Recomendaciones_TB> MH_Recomendaciones_TB { get; set; }
    }
}
