//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_PlanillaPeriodoConfig_TB
    {
        public int IdConfig { get; set; }
        public string TipoPeriodo { get; set; }
        public bool Activo { get; set; }
    }
}
