//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_PlanillaDetalle_TB
    {
        public long IdPlanillaDetalle { get; set; }
        public long IdPlanilla { get; set; }
        public int IdUsuario { get; set; }
        public decimal HorasNormales { get; set; }
        public decimal HorasExtra { get; set; }
        public decimal HorasDoble { get; set; }
        public decimal SalarioHora { get; set; }
        public decimal MontoNormales { get; set; }
        public decimal MontoExtra { get; set; }
        public decimal MontoDoble { get; set; }
        public decimal TotalPagar { get; set; }
    
        public virtual MH_Planilla_TB MH_Planilla_TB { get; set; }
        public virtual MH_Usuario_TB MH_Usuario_TB { get; set; }
    }
}
