//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_Planilla_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MH_Planilla_TB()
        {
            this.MH_PlanillaDetalle_TB = new HashSet<MH_PlanillaDetalle_TB>();
        }
    
        public long IdPlanilla { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public System.DateTime FechaCalculo { get; set; }
        public string Observacion { get; set; }
        public bool Cerrada { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public Nullable<int> CerradaPorIdUsuario { get; set; }
        public string MotivoCierre { get; set; }
    
        public virtual MH_Usuario_TB MH_Usuario_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_PlanillaDetalle_TB> MH_PlanillaDetalle_TB { get; set; }
    }
}
