//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_Productos_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MH_Productos_TB()
        {
            this.MH_DetalleFactura_TB = new HashSet<MH_DetalleFactura_TB>();
        }
    
        public int IdProducto { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public string NombreProducto { get; set; }
        public string Descripcion { get; set; }
        public string Categoria { get; set; }
        public decimal PrecioUnitario { get; set; }
        public int StockActual { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public string ImagenUrl { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_DetalleFactura_TB> MH_DetalleFactura_TB { get; set; }
        public virtual MH_Estado_TB MH_Estado_TB { get; set; }
        public virtual MH_Proveedor_TB MH_Proveedor_TB { get; set; }
    }
}
