//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_Permiso_TB
    {
        public long IdPermiso { get; set; }
        public int IdUsuario { get; set; }
        public int IdTipoPermiso { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string Motivo { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public Nullable<int> IdAdminResolucion { get; set; }
        public Nullable<System.DateTime> FechaResolucion { get; set; }
        public string ComentarioAdmin { get; set; }
    
        public virtual MH_Usuario_TB MH_Usuario_TB { get; set; }
        public virtual MH_TipoPermiso_TB MH_TipoPermiso_TB { get; set; }
        public virtual MH_Usuario_TB MH_Usuario_TB1 { get; set; }
    }
}
