//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_PlanillaDetalle_TB
    {
        public long IdPlanillaDetalle { get; set; }
        public long IdPlanilla { get; set; }
        public int IdUsuario { get; set; }
        public decimal HorasNormales { get; set; }
        public decimal HorasExtra { get; set; }
        public decimal HorasDoble { get; set; }
        public decimal SalarioHora { get; set; }
        public decimal MontoNormales { get; set; }
        public decimal MontoExtra { get; set; }
        public decimal MontoDoble { get; set; }
        public decimal TotalPagar { get; set; }
    
        public virtual MH_Planilla_TB MH_Planilla_TB { get; set; }
        public virtual MH_Usuario_TB MH_Usuario_TB { get; set; }
    }
}
