//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_Recomendaciones_TB
    {
        public int IdRecomendacion { get; set; }
        public int IdCita { get; set; }
        public int IdMascota { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual MH_Cita_TB MH_Cita_TB { get; set; }
        public virtual MH_Mascotas_TB MH_Mascotas_TB { get; set; }
    }
}
