//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_Recomendaciones_TB
    {
        public int IdRecomendacion { get; set; }
        public int IdCita { get; set; }
        public int IdMascota { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual MH_Cita_TB MH_Cita_TB { get; set; }
        public virtual MH_Mascotas_TB MH_Mascotas_TB { get; set; }
    }
}
