//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_Servicio_Producto_TB
    {
        public int IdServicioProducto { get; set; }
        public int IdServicio { get; set; }
        public int IdProducto { get; set; }
    
        public virtual MH_Productos_TB MH_Productos_TB { get; set; }
        public virtual MH_Servicios_TB MH_Servicios_TB { get; set; }
    }
}
