//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_Servicio_Producto_TB
    {
        public int IdServicioProducto { get; set; }
        public int IdServicio { get; set; }
        public int IdProducto { get; set; }
    
        public virtual MH_Productos_TB MH_Productos_TB { get; set; }
        public virtual MH_Servicios_TB MH_Servicios_TB { get; set; }
    }
}
