//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_TipoPermiso_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MH_TipoPermiso_TB()
        {
            this.MH_Permiso_TB = new HashSet<MH_Permiso_TB>();
        }
    
        public int IdTipoPermiso { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public bool RequiereDoc { get; set; }
        public bool AfectaSalario { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_Permiso_TB> MH_Permiso_TB { get; set; }
    }
}
