//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_Usuario_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MH_Usuario_TB()
        {
            this.MH_Cita_TB = new HashSet<MH_Cita_TB>();
            this.MH_Comision_TB = new HashSet<MH_Comision_TB>();
            this.MH_EmpleadoJornada_TB = new HashSet<MH_EmpleadoJornada_TB>();
            this.MH_EmpleadoLaboral_TB = new HashSet<MH_EmpleadoLaboral_TB>();
            this.MH_Factura_TB = new HashSet<MH_Factura_TB>();
            this.MH_Marcacion_TB = new HashSet<MH_Marcacion_TB>();
            this.MH_Mascotas_TB = new HashSet<MH_Mascotas_TB>();
            this.MH_Permiso_TB = new HashSet<MH_Permiso_TB>();
            this.MH_Permiso_TB1 = new HashSet<MH_Permiso_TB>();
            this.MH_Planilla_TB = new HashSet<MH_Planilla_TB>();
            this.MH_PlanillaDetalle_TB = new HashSet<MH_PlanillaDetalle_TB>();
        }
    
        public int IdUsuario { get; set; }
        public int IdTipoUsuario { get; set; }
        public Nullable<int> IdDireccion { get; set; }
        public string NombreCompleto { get; set; }
        public string Correo { get; set; }
        public string ContrasennaHash { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_Cita_TB> MH_Cita_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_Comision_TB> MH_Comision_TB { get; set; }
        public virtual MH_Direccion_TB MH_Direccion_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_EmpleadoJornada_TB> MH_EmpleadoJornada_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_EmpleadoLaboral_TB> MH_EmpleadoLaboral_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_Factura_TB> MH_Factura_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_Marcacion_TB> MH_Marcacion_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_Mascotas_TB> MH_Mascotas_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_Permiso_TB> MH_Permiso_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_Permiso_TB> MH_Permiso_TB1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_Planilla_TB> MH_Planilla_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_PlanillaDetalle_TB> MH_PlanillaDetalle_TB { get; set; }
        public virtual MH_Tipo_Usuario_TB MH_Tipo_Usuario_TB { get; set; }
    }
}
