//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_Usuario_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MH_Usuario_TB()
        {
            this.MH_Cita_TB = new HashSet<MH_Cita_TB>();
            this.MH_Factura_TB = new HashSet<MH_Factura_TB>();
            this.MH_Mascotas_TB = new HashSet<MH_Mascotas_TB>();
            this.MH_Marcacion_TB = new HashSet<MH_Marcacion_TB>();
        }
    
        public int IdUsuario { get; set; }
        public int IdTipoUsuario { get; set; }
        public Nullable<int> IdDireccion { get; set; }
        public string NombreCompleto { get; set; }
        public string Correo { get; set; }
        public string ContrasennaHash { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> IdJornada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_Cita_TB> MH_Cita_TB { get; set; }
        public virtual MH_Direccion_TB MH_Direccion_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_Factura_TB> MH_Factura_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_Mascotas_TB> MH_Mascotas_TB { get; set; }
        public virtual MH_Tipo_Usuario_TB MH_Tipo_Usuario_TB { get; set; }
        public virtual MH_Jornada_TB MH_Jornada_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MH_Marcacion_TB> MH_Marcacion_TB { get; set; }
    }
}
