//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_MiMundoHuellitasEntities : DbContext
    {
        public BD_MiMundoHuellitasEntities()
            : base("name=BD_MiMundoHuellitasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MH_Canton_TB> MH_Canton_TB { get; set; }
        public virtual DbSet<MH_Cita_TB> MH_Cita_TB { get; set; }
        public virtual DbSet<MH_DetalleFactura_TB> MH_DetalleFactura_TB { get; set; }
        public virtual DbSet<MH_Direccion_TB> MH_Direccion_TB { get; set; }
        public virtual DbSet<MH_Distrito_TB> MH_Distrito_TB { get; set; }
        public virtual DbSet<MH_Especie_TB> MH_Especie_TB { get; set; }
        public virtual DbSet<MH_Estado_TB> MH_Estado_TB { get; set; }
        public virtual DbSet<MH_Factura_TB> MH_Factura_TB { get; set; }
        public virtual DbSet<MH_Mascotas_TB> MH_Mascotas_TB { get; set; }
        public virtual DbSet<MH_Productos_TB> MH_Productos_TB { get; set; }
        public virtual DbSet<MH_Proveedor_TB> MH_Proveedor_TB { get; set; }
        public virtual DbSet<MH_Provincia_TB> MH_Provincia_TB { get; set; }
        public virtual DbSet<MH_Raza_TB> MH_Raza_TB { get; set; }
        public virtual DbSet<MH_Servicios_Cita_TB> MH_Servicios_Cita_TB { get; set; }
        public virtual DbSet<MH_Servicios_TB> MH_Servicios_TB { get; set; }
        public virtual DbSet<MH_Tipo_Usuario_TB> MH_Tipo_Usuario_TB { get; set; }
        public virtual DbSet<MH_Usuario_TB> MH_Usuario_TB { get; set; }
    }
}
