//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MH_AsistenciaDiaria
    {
        public int IdUsuario { get; set; }
        public string NombreCompleto { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> HoraEntradaMin { get; set; }
        public Nullable<System.DateTime> HoraSalidaMax { get; set; }
        public Nullable<decimal> HorasNormalesDia { get; set; }
        public Nullable<decimal> HorasTrabajadas { get; set; }
        public int EsFeriado { get; set; }
        public int EsFinDeSemana { get; set; }
    }
}
