//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiMundoHuellitas.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MH_AsistenciaDiaria
    {
        public int IdUsuario { get; set; }
        public string NombreCompleto { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> HoraEntradaMin { get; set; }
        public Nullable<System.DateTime> HoraSalidaMax { get; set; }
        public Nullable<decimal> HorasNormalesDia { get; set; }
        public Nullable<decimal> HorasTrabajadas { get; set; }
        public int EsFeriado { get; set; }
        public int EsFinDeSemana { get; set; }
    }
}
